# Generated by Django 5.2.5 on 2025-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uploaded PDF',
                'verbose_name_plural': 'Uploaded PDFs',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['uploaded_at'], name='pdfupload_u_uploade_0ff579_idx')],
            },
        ),
    ]
